name: run 

on:
 workflow_dispatch: 
 schedule:  
  - cron: '30 23 * * *' 
jobs: 
  build: 
   runs-on: ubuntu-latest  
   steps: 
   - uses: actions/checkout@v2 
   - name: Set up Python 3.9 
     uses: actions/setup-python@v4 
     with: 
      python-version: 3.9 
      
   - name: Install dependencies
     run: | 
       python -m pip install --upgrade pip 
       pip3 install -r requirements.txt 
   - name: dat-push
     run: | 
      python ./main.py 
