name: Python package
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'
      jobs:
        build:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2
            - name: Set up Python Python 3.9
              uses: actions/setup-python@v2
              with:
                python-version: 3.9.1
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip 

                ip3 install -r requirements.txt 
            - name: dat-push
              run: |
                python ./main.py 
